<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCachedBuildingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable('cached_buildings')) {
            Schema::create('cached_buildings', function (Blueprint $table) {
                $table->increments('id');
                $table->unsignedInteger('audit_id');
                $table->unsignedInteger('project_id')->nullable();
                $table->unsignedInteger('amenity_id')->nullable();
                $table->string('status', 100)->nullable();
                $table->string('type', 100)->nullable();
                $table->integer('type_total')->nullable();
                $table->string('type_text', 100)->nullable();
                $table->string('type_text_plural', 100)->nullable();
                $table->integer('finding_total')->nullable();
                $table->string('finding_file_status', 100)->nullable();
                $table->string('finding_nlt_status', 100)->nullable();
                $table->string('finding_lt_status', 100)->nullable();
                $table->string('finding_sd_status', 100)->nullable();
                $table->integer('finding_file_total')->nullable();
                $table->integer('finding_file_completed')->nullable();
                $table->integer('finding_nlt_total')->nullable();
                $table->integer('finding_nlt_completed')->nullable();
                $table->integer('finding_lt_total')->nullable();
                $table->integer('finding_lt_completed')->nullable();
                $table->integer('finding_sd_total')->nullable();
                $table->integer('finding_sd_completed')->nullable();
                $table->integer('program_total')->nullable();
                $table->date('followup_date')->nullable();
                $table->string('address', 250)->nullable();
                $table->string('city', 250)->nullable();
                $table->string('state', 100)->nullable();
                $table->string('zip', 100)->nullable();
                $table->json('auditors_json')->nullable();
                $table->json('amenities_json')->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cached_buildings');
    }
}
