<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateProjectDetailsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable('project_details')) {
            Schema::create('project_details', function (Blueprint $table) {
                $table->increments('id');
                $table->unsignedInteger('project_id');
                $table->unsignedInteger('audit_id')->nullable();
                $table->date('last_audit_completed')->nullable();
                $table->date('next_audit_due')->nullable();
                $table->integer('score_percentage')->nullable();
                $table->string('score', 10)->nullable();
                $table->integer('total_building')->nullable();
                $table->integer('total_building_common_areas')->nullable();
                $table->integer('total_project_common_areas')->nullable();
                $table->integer('total_units')->nullable();
                $table->integer('market_rate')->nullable();
                $table->integer('subsidized')->nullable();
                $table->json('programs')->nullable();
                $table->string('owner_name', 255)->nullable();
                $table->string('owner_poc', 255)->nullable();
                $table->string('owner_phone', 255)->nullable();
                $table->string('owner_fax', 255)->nullable();
                $table->string('owner_email', 255)->nullable();
                $table->string('owner_address', 255)->nullable();
                $table->string('owner_address2', 255)->nullable();
                $table->string('owner_city', 255)->nullable();
                $table->string('owner_state', 20)->nullable();
                $table->string('owner_zip', 20)->nullable();
                $table->string('manager_name', 255)->nullable();
                $table->string('manager_poc', 255)->nullable();
                $table->string('manager_phone', 255)->nullable();
                $table->string('manager_fax', 255)->nullable();
                $table->string('manager_email', 255)->nullable();
                $table->string('manager_address', 255)->nullable();
                $table->string('manager_address2', 255)->nullable();
                $table->string('manager_city', 255)->nullable();
                $table->string('manager_state', 20)->nullable();
                $table->string('manager_zip', 20)->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('project_details');
    }
}
