<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateComplianceContactsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (! Schema::hasTable('compliance_contacts')) {
            Schema::create('compliance_contacts', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('compliance_contact_key')->nullable();
                $table->integer('project_key')->nullable();
                $table->unsignedInteger('project_id')->nullable();
                $table->string('address', 255)->nullable();
                $table->string('city', 255)->nullable();
                $table->string('zip', 5)->nullable();
                $table->string('note')->nullable();
                $table->string('email', 255)->nullable();
                $table->string('phone', 255)->nullable();
                $table->string('review_cycle', 255)->nullable();
                $table->timestamp('next_inspection')->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('compliance_contacts');
    }
}
