<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateProjectsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (! Schema::hasTable('projects')) {
            Schema::create('projects', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('project_key')->nullable();
                $table->string('project_name', 255)->nullable();
                $table->integer('physical_address_key')->nullable();
                $table->integer('default_phone_number_key')->nullable();
                $table->integer('default_fax_number_key')->nullable();
                $table->unsignedInteger('default_fax_number_id')->nullable();
                $table->integer('total_unit_count')->nullable();
                $table->integer('total_building_count')->nullable();
                $table->string('project_number', 255)->nullable();
                $table->integer('sample_size')->nullable();
                $table->timestamp('last_edited', 3)->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('projects');
    }
}
