<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHouseHoldEventsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (! Schema::hasTable('house_hold_events')) {
            Schema::create('house_hold_events', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('house_hold_event_key')->nullable();
                $table->unsignedInteger('owner_year_certification_id')->nullable();
                $table->integer('owner_year_certification_key')->nullable();
                $table->unsignedInteger('project_id')->nullable();
                $table->integer('project_key')->nullable();
                $table->unsignedInteger('house_hold_id')->nullable();
                $table->integer('house_hold_key')->nullable();
                $table->unsignedInteger('unit_id')->nullable();
                $table->integer('unit_key')->nullable();
                $table->timestamp('event_date')->nullable();
                $table->unsignedInteger('event_type_id')->nullable();
                $table->integer('event_type_key')->nullable();
                $table->unsignedInteger('unit_status_id')->nullable();
                $table->integer('unit_status_key')->nullable();
                $table->float('current_income')->nullable();
                $table->unsignedInteger('rent_level_id')->nullable();
                $table->integer('rent_level_key')->nullable();
                $table->unsignedInteger('income_level_id')->nullable();
                $table->integer('income_level_key')->nullable();
                $table->float('tenant_rent_portion')->nullable();
                $table->float('rental_assistance_amount')->nullable();
                $table->float('utility_allowance')->nullable();
                $table->float('household_count')->nullable();
                $table->float('student_count')->nullable();
                $table->tinyInteger('all_student_house')->nullable();
                $table->unsignedInteger('student_explanation_id')->nullable();
                $table->integer('student_explanation_key')->nullable();
                $table->unsignedInteger('utility_allowance_id')->nullable();
                $table->integer('utility_allowance_key')->nullable();
                $table->unsignedInteger('rental_assistance_id')->nullable();
                $table->integer('rental_assistance_key')->nullable();
                $table->unsignedInteger('rental_assistance_source_id')->nullable();
                $table->integer('rental_assistance_source_key')->nullable();
                $table->string('notes')->nullable();
                $table->unsignedInteger('unit_identity_id')->nullable();
                $table->integer('unit_identity_key')->nullable();
                $table->timestamp('certification_date')->nullable();
                $table->timestamp('last_edited', 3)->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('house_hold_events');
    }
}
