<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHouseholdsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (! Schema::hasTable('households')) {
            Schema::create('households', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('house_hold_key')->nullable();
                $table->unsignedInteger('project_id')->nullable();
                $table->integer('development_key')->nullable();
                $table->unsignedInteger('unit_id')->nullable();
                $table->integer('unit_key')->nullable();
                $table->unsignedInteger('household_size_id')->nullable();
                $table->integer('household_size_key')->nullable();
                $table->unsignedInteger('household_size_move_in_id')->nullable();
                $table->integer('household_size_move_in_key')->nullable();
                $table->float('household_income_move_in')->nullable();
                $table->timestamp('initial_move_in_date')->nullable();
                $table->unsignedInteger('special_needs_id')->nullable();
                $table->integer('special_needs_key')->nullable();
                $table->string('head_of_household_name', 255)->nullable();
                $table->timestamp('last_edited', 3)->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('households');
    }
}
