<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUnitAmenitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (! Schema::hasTable('unit_amenities')) {
            Schema::create('unit_amenities', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('unit_amenity_key')->nullable();
                $table->unsignedInteger('unit_id')->nullable();
                $table->integer('unit_key')->nullable();
                $table->integer('amenity_type_key')->nullable();
                $table->unsignedInteger('amenity_id')->nullable();
                $table->string('comment', 255)->nullable();
                $table->timestamp('last_edited', 3)->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('unit_amenities');
    }
}
