<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCachedCommentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable('cached_comments')) {
            Schema::create('cached_comments', function (Blueprint $table) {
                $table->increments('id');
                $table->unsignedInteger('audit_id');
                $table->unsignedInteger('building_id')->nullable();
                $table->unsignedInteger('project_id')->nullable();
                $table->unsignedInteger('finding_id')->nullable();
                $table->unsignedInteger('unit_id')->nullable();
                $table->unsignedInteger('parent_id')->nullable();
                $table->unsignedInteger('user_id')->nullable();
                $table->string('user_name', 100)->nullable();
                $table->json('user_json')->nullable();
                $table->string('status', 100)->nullable();
                $table->string('type', 100)->nullable();
                $table->string('type_icon', 100)->nullable();
                $table->string('type_text', 100)->nullable();
                $table->text('content')->nullable();
                $table->string('finding_type', 100)->nullable();
                $table->unsignedInteger('document_id')->nullable();
                $table->json('document_json')->nullable();
                $table->json('photos_json')->nullable();
                $table->date('followup_date')->nullable();
                $table->unsignedInteger('followup_assigned_id')->nullable();
                $table->string('followup_assigned_name', 100)->nullable();
                $table->json('followup_actions_json')->nullable();
                $table->json('actions_json')->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cached_comments');
    }
}
