<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHouseHoldSizesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (! Schema::hasTable('house_hold_sizes')) {
            Schema::create('house_hold_sizes', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('house_hold_size_key')->nullable();
                $table->integer('house_hold_size')->nullable();
                $table->string('house_hold_size_description')->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('house_hold_sizes');
    }
}
