<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSyncOrganizationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (! Schema::hasTable('sync_organizations')) {
            Schema::create('sync_organizations', function (Blueprint $table) {
                $table->increments('id');
                $table->unsignedInteger('allita_id')->nullable();
                $table->integer('organization_key')->nullable();
                $table->integer('default_address_key')->nullable();
                $table->integer('default_phone_number_key')->nullable();
                $table->integer('default_fax_number_key')->nullable();
                $table->integer('default_contact_person_key')->nullable();
                $table->integer('parent_organization_key')->nullable();
                $table->string('organization_name', 255)->nullable();
                $table->string('fed_id_number', 255)->nullable();
                $table->tinyInteger('is_active')->nullable();
                $table->timestamp('last_edited', 3)->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sync_organizations');
    }
}
