<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAmenitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (! Schema::hasTable('amenities')) {
            Schema::create('amenities', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('amenity_type_key')->nullable();
                $table->string('amenity_description', 255)->nullable();
                $table->tinyInteger('project')->nullable();
                $table->tinyInteger('building')->nullable();
                $table->tinyInteger('unit')->nullable();
                $table->tinyInteger('inspectable')->nullable();
                $table->string('policy', 100)->nullable();
                $table->float('time_to_complete')->nullable()->default(1);
                $table->timestamp('last_edited', 3)->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('amenities');
    }
}
