<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUtilityAllowancesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable('utility_allowances')) {
            Schema::create('utility_allowances', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('utility_allowance_key')->nullable();
                $table->integer('utility_allowance_type_id')->nullable();
                $table->string('utility_allowance_description')->nullable();
                $table->integer('utility_allowance_type_key')->nullable();
                $table->timestamp('effective_date')->nullable();
                $table->timestamp('effective_date2')->nullable();
                $table->timestamp('last_edited', 3)->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('utility_allowances');
    }
}
