<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSyncHouseHoldEventsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable('sync_house_hold_events')) {
            Schema::create('sync_house_hold_events', function (Blueprint $table) {
                $table->increments('id');
                $table->unsignedInteger('allita_id')->nullable();
                $table->integer('house_hold_event_key')->nullable();
                $table->integer('owner_year_certification_key')->nullable();
                $table->integer('project_key')->nullable();
                $table->integer('house_hold_key')->nullable();
                $table->integer('unit_key')->nullable();
                $table->timestamp('event_date')->nullable();
                $table->integer('event_type_key')->nullable();
                $table->integer('unit_status_key')->nullable();
                $table->float('current_income')->nullable();
                $table->integer('rent_level_key')->nullable();
                $table->integer('income_level_key')->nullable();
                $table->float('tenant_rent_portion')->nullable();
                $table->float('rental_assistance_amount')->nullable();
                $table->float('utility_allowance')->nullable();
                $table->float('household_count')->nullable();
                $table->float('student_count')->nullable();
                $table->tinyInteger('all_student_house')->nullable();
                $table->integer('student_explanation_key')->nullable();
                $table->integer('utility_allowance_key')->nullable();
                $table->integer('rental_assistance_key')->nullable();
                $table->integer('rental_assistance_source_key')->nullable();
                $table->string('notes')->nullable();
                $table->integer('unit_identity_key')->nullable();
                $table->timestamp('certification_date')->nullable();
                $table->timestamp('last_edited', 3)->nullable();
                $table->nullableTimestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sync_house_hold_events');
    }
}
