<?php

use Illuminate\Database\Seeder;

class CashedAuditsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $auditsSeeder = [
            [
                'id' => '123', // this is the audit id, when displayed, add leading zeros?
                'project_id' => '19200114', // this is the project id from Devco, rename project_id
                'status' => 'critical',
                'lead' => 1, // id
                'lead_json' => '{
					"id": "1",
					"name": "Brian Greenwood",
					"initials": "BG",
					"color": "green",
					"status": "warning"
				}',
                'title' => 'Great American Apartments',
                'pm' => 'THE NOT SO LONG PROPERTY MANAGER NAME', // PM name, not subtitle! 
                'address' => '3045 Cumberland Woods Street, Suite 20',
                'city' => 'COLUMBUS',
                'state' => 'OH',
                'zip' => '43219',
                'total_buildings' => '10',
                'inspection_status' => 'action-needed',
                'inspection_status_text' => 'Inspection in progress',
                'inspection_schedule_date' => '2018-12-21', // combine and use one date for both fields
                'inspection_schedule_text' => 'Inspection in progress',
                'inspectable_items' => '10',
                'total_items' => '21',
                'audit_compliance_icon' => 'a-circle-checked',
                'audit_compliance_status' => 'ok-actionable', 
                'audit_compliance_status_text' => 'Audit Compliant',
                'followup_status' => 'ok-actionable',
                'followup_status_text' => 'No followups',
                'followup_date' => '2018-12-10', // combine and use one date for both fields
                'file_audit_icon' => 'a-folder',
                'file_audit_status' => 'ok-actionable',
                'file_audit_status_text' => '',
                'nlt_audit_icon' => 'a-booboo',
                'nlt_audit_status' => 'action-required',
                'nlt_audit_status_text' => '',
                'lt_audit_icon' => 'a-skull',
                'lt_audit_status' => 'in-progress',
                'lt_audit_status_text' => '',
                'smoke_audit_icon' => 'a-flames',
                'smoke_audit_status' => 'action-needed',
                'smoke_audit_status_text' => '',
                'auditor_status_icon' => 'a-avatar',
                'auditor_status' => 'action-required',
                'auditor_status_text' => 'Auditors / schedule conflicts / unasigned items',
                'message_status_icon' => 'a-envelope-4',
                'message_status' => '',
                'message_status_text' => '',
                'document_status_icon' => 'a-files',
                'document_status' => '',
                'document_status_text' => 'Document status',
                'history_status_icon' => 'a-person-clock',
                'history_status' => '',
                'history_status_text' => 'NO/VIEW HISTORY',
                'step_status_icon' => 'a-calendar-7',
                'step_status' => 'no-action',
                'step_status_text' => ''
            ],
            [
                'id' => '456',
                'project_id' => '19200115',
                'status' => 'no-action',
                'lead' => 2, // id
                'lead_json' => '{
					"id": "2",
					"name": "Brian Greenwood 2",
					"initials": "BG",
					"color": "green",
					"status": "warning"
				}',
                'title' => 'Great American Apartments',
                'pm' => 'THE NOT SO LONG PROPERTY MANAGER NAME',
                'address' => '3045 Cumberland Woods Street, Suite 20',
                'city' => 'COLUMBUS',
                'state' => 'OH',
                'zip' => '43219',
                'total_buildings' => '10',
                'inspection_status' => 'action-needed',
                'inspection_status_text' => 'Inspection in progress',
                'inspection_schedule_date' => '2018-12-21',
                'inspection_schedule_text' => 'Inspection in progress',
                'inspectable_items' => '10',
                'total_items' => '21',
                'audit_compliance_icon' => 'a-circle-checked',
                'audit_compliance_status' => 'ok-actionable', 
                'audit_compliance_status_text' => 'Audit Compliant',
                'followup_status' => 'ok-actionable',
                'followup_status_text' => 'No followups',
                'followup_date' => '2018-12-10',
                'file_audit_icon' => 'a-folder',
                'file_audit_status' => 'ok-actionable',
                'file_audit_status_text' => '',
                'nlt_audit_icon' => 'a-booboo',
                'nlt_audit_status' => 'action-required',
                'nlt_audit_status_text' => '',
                'lt_audit_icon' => 'a-skull',
                'lt_audit_status' => 'in-progress',
                'lt_audit_status_text' => '',
                'smoke_audit_icon' => 'a-flames',
                'smoke_audit_status' => 'action-needed',
                'smoke_audit_status_text' => '',
                'auditor_status_icon' => 'a-avatar',
                'auditor_status' => 'action-required',
                'auditor_status_text' => 'Auditors / schedule conflicts / unasigned items',
                'message_status_icon' => 'a-envelope-4',
                'message_status' => '',
                'message_status_text' => '',
                'document_status_icon' => 'a-files',
                'document_status' => '',
                'document_status_text' => 'Document status',
                'history_status_icon' => 'a-person-clock',
                'history_status' => '',
                'history_status_text' => 'NO/VIEW HISTORY',
                'step_status_icon' => 'a-calendar-7',
                'step_status' => 'no-action',
                'step_status_text' => ''
            ],
            [
                'id' => '789',
                'project_id' => '19200116',
                'status' => 'action-needed',
                'lead' => 3, // id
                'lead_json' => '{
					"id": "3",
					"name": "Brian Greenwood 3",
					"initials": "BG",
					"color": "green",
					"status": "warning"
				}',
                'title' => 'Great American Apartments',
                'pm' => 'THE NOT SO LONG PROPERTY MANAGER NAME',
                'address' => '3045 Cumberland Woods Street, Suite 20',
                'city' => 'COLUMBUS',
                'state' => 'OH',
                'zip' => '43219',
                'total_buildings' => '10',
                'inspection_status' => 'action-needed',
                'inspection_status_text' => 'Inspection in progress',
                'inspection_schedule_date' => '2018-12-21',
                'inspection_schedule_text' => 'Inspection in progress',
                'inspectable_items' => '10',
                'total_items' => '21',
                'audit_compliance_icon' => 'a-circle-checked',
                'audit_compliance_status' => 'ok-actionable', 
                'audit_compliance_status_text' => 'Audit Compliant',
                'followup_status' => 'ok-actionable',
                'followup_status_text' => 'No followups',
                'followup_date' => '2018-12-10',
                'file_audit_icon' => 'a-folder',
                'file_audit_status' => 'ok-actionable',
                'file_audit_status_text' => '',
                'nlt_audit_icon' => 'a-booboo',
                'nlt_audit_status' => 'action-required',
                'nlt_audit_status_text' => '',
                'lt_audit_icon' => 'a-skull',
                'lt_audit_status' => 'in-progress',
                'lt_audit_status_text' => '',
                'smoke_audit_icon' => 'a-flames',
                'smoke_audit_status' => 'action-needed',
                'smoke_audit_status_text' => '',
                'auditor_status_icon' => 'a-avatar',
                'auditor_status' => 'action-required',
                'auditor_status_text' => 'Auditors / schedule conflicts / unasigned items',
                'message_status_icon' => 'a-envelope-4',
                'message_status' => '',
                'message_status_text' => '',
                'document_status_icon' => 'a-files',
                'document_status' => '',
                'document_status_text' => 'Document status',
                'history_status_icon' => 'a-person-clock',
                'history_status' => '',
                'history_status_text' => 'NO/VIEW HISTORY',
                'step_status_icon' => 'a-calendar-7',
                'step_status' => 'no-action',
                'step_status_text' => ''
            ],
            [
                'id' => '222',
                'project_id' => '19200133',
                'status' => 'critical',
                'lead' => 4, // id
                'lead_json' => '{
					"id": "4",
					"name": "Brian Greenwood 4",
					"initials": "BG",
					"color": "green",
					"status": "warning"
				}',
                'title' => 'Great American Apartments',
                'pm' => 'THE NOT SO LONG PROPERTY MANAGER NAME',
                'address' => '3045 Cumberland Woods Street, Suite 20',
                'city' => 'COLUMBUS',
                'state' => 'OH',
                'zip' => '43219',
                'total_buildings' => '10',
                'inspection_status' => 'action-needed',
                'inspection_status_text' => 'Inspection in progress',
                'inspection_schedule_date' => '2018-12-21',
                'inspection_schedule_text' => 'Inspection in progress',
                'inspectable_items' => '10',
                'total_items' => '21',
                'audit_compliance_icon' => 'a-circle-checked',
                'audit_compliance_status' => 'ok-actionable', 
                'audit_compliance_status_text' => 'Audit Compliant',
                'followup_status' => 'ok-actionable',
                'followup_status_text' => 'No followups',
                'followup_date' => '2018-12-10',
                'file_audit_icon' => 'a-folder',
                'file_audit_status' => 'ok-actionable',
                'file_audit_status_text' => '',
                'nlt_audit_icon' => 'a-booboo',
                'nlt_audit_status' => 'action-required',
                'nlt_audit_status_text' => '',
                'lt_audit_icon' => 'a-skull',
                'lt_audit_status' => 'in-progress',
                'lt_audit_status_text' => '',
                'smoke_audit_icon' => 'a-flames',
                'smoke_audit_status' => 'action-needed',
                'smoke_audit_status_text' => '',
                'auditor_status_icon' => 'a-avatar',
                'auditor_status' => 'action-required',
                'auditor_status_text' => 'Auditors / schedule conflicts / unasigned items',
                'message_status_icon' => 'a-envelope-4',
                'message_status' => '',
                'message_status_text' => '',
                'document_status_icon' => 'a-files',
                'document_status' => '',
                'document_status_text' => 'Document status',
                'history_status_icon' => 'a-person-clock',
                'history_status' => '',
                'history_status_text' => 'NO/VIEW HISTORY',
                'step_status_icon' => 'a-calendar-7',
                'step_status' => 'no-action',
                'step_status_text' => ''
            ],
            [
                'id' => '445',
                'project_id' => '19200234',
                'status' => 'ok-actionable',
                'lead' => 5, // id
                'lead_json' => '{
					"id": "5",
					"name": "Brian Greenwood 5",
					"initials": "BG",
					"color": "green",
					"status": "warning"
				}',
                'title' => 'Great American Apartments',
                'pm' => 'THE NOT SO LONG PROPERTY MANAGER NAME',
                'address' => '3045 Cumberland Woods Street, Suite 20',
                'city' => 'COLUMBUS',
                'state' => 'OH',
                'zip' => '43219',
                'total_buildings' => '10',
                'inspection_status' => 'action-needed',
                'inspection_status_text' => 'Inspection in progress',
                'inspection_schedule_date' => '2018-12-17',
                'inspection_schedule_text' => 'Inspection in progress',
                'inspectable_items' => '10',
                'total_items' => '21',
                'audit_compliance_icon' => 'a-circle-checked',
                'audit_compliance_status' => 'ok-actionable', 
                'audit_compliance_status_text' => 'Audit Compliant',
                'followup_status' => 'ok-actionable',
                'followup_status_text' => 'No followups',
                'followup_date' => '2018-12-10',
                'file_audit_icon' => 'a-folder',
                'file_audit_status' => 'ok-actionable',
                'file_audit_status_text' => '',
                'nlt_audit_icon' => 'a-booboo',
                'nlt_audit_status' => 'action-required',
                'nlt_audit_status_text' => '',
                'lt_audit_icon' => 'a-skull',
                'lt_audit_status' => 'in-progress',
                'lt_audit_status_text' => '',
                'smoke_audit_icon' => 'a-flames',
                'smoke_audit_status' => 'action-needed',
                'smoke_audit_status_text' => '',
                'auditor_status_icon' => 'a-avatar',
                'auditor_status' => 'action-required',
                'auditor_status_text' => 'Auditors / schedule conflicts / unasigned items',
                'message_status_icon' => 'a-envelope-4',
                'message_status' => '',
                'message_status_text' => '',
                'document_status_icon' => 'a-files',
                'document_status' => '',
                'document_status_text' => 'Document status',
                'history_status_icon' => 'a-person-clock',
                'history_status' => '',
                'history_status_text' => 'NO/VIEW HISTORY',
                'step_status_icon' => 'a-calendar-7',
                'step_status' => 'no-action',
                'step_status_text' => ''
            ],
            [
                'id' => '334',
                'project_id' => '19200221',
                'status' => 'action-needed',
                'lead' => 6, // id
                'lead_json' => '{
					"id": "6",
					"name": "Brian Greenwood 6",
					"initials": "BG",
					"color": "green",
					"status": "warning"
				}',
                'title' => 'Great American Apartments',
                'pm' => 'THE NOT SO LONG PROPERTY MANAGER NAME',
                'address' => '3045 Cumberland Woods Street, Suite 20',
                'city' => 'COLUMBUS',
                'state' => 'OH',
                'zip' => '43219',
                'total_buildings' => '10',
                'inspection_status' => 'action-needed',
                'inspection_status_text' => 'Inspection in progress',
                'inspection_schedule_date' => '2018-12-21',
                'inspection_schedule_text' => 'Inspection in progress',
                'inspectable_items' => '10',
                'total_items' => '21',
                'audit_compliance_icon' => 'a-circle-checked',
                'audit_compliance_status' => 'ok-actionable', 
                'audit_compliance_status_text' => 'Audit Compliant',
                'followup_status' => 'ok-actionable',
                'followup_status_text' => 'No followups',
                'followup_date' => '2018-12-10',
                'file_audit_icon' => 'a-folder',
                'file_audit_status' => 'ok-actionable',
                'file_audit_status_text' => '',
                'nlt_audit_icon' => 'a-booboo',
                'nlt_audit_status' => 'action-required',
                'nlt_audit_status_text' => '',
                'lt_audit_icon' => 'a-skull',
                'lt_audit_status' => 'in-progress',
                'lt_audit_status_text' => '',
                'smoke_audit_icon' => 'a-flames',
                'smoke_audit_status' => 'action-needed',
                'smoke_audit_status_text' => '',
                'auditor_status_icon' => 'a-avatar',
                'auditor_status' => 'action-required',
                'auditor_status_text' => 'Auditors / schedule conflicts / unasigned items',
                'message_status_icon' => 'a-envelope-4',
                'message_status' => '',
                'message_status_text' => '',
                'document_status_icon' => 'a-files',
                'document_status' => '',
                'document_status_text' => 'Document status',
                'history_status_icon' => 'a-person-clock',
                'history_status' => '',
                'history_status_text' => 'NO/VIEW HISTORY',
                'step_status_icon' => 'a-calendar-7',
                'step_status' => 'no-action',
                'step_status_text' => ''
            ]
        ];

        \Illuminate\Support\Facades\DB::table('cached_audits')->insert($auditsSeeder);
    }
}
