<?php

use Illuminate\Database\Seeder;

class EntitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // ACCOUNTING SUPPORT DATA

        $entitiesData = array(
            array(
                'entity_name'=>'Ohio Housing Finance Agency.',
                'user_id'=>'2',
                'active'=>'1',
                'address1'=>'57 E Main Street',
                'address2'=>'',
                'city'=>'Columbus',
                'state_id'=>'36',
                'zip'=>'43215',
                'phone'=>'(614) 466-7970',
                'fax'=>'',
                'web_address'=>'http://www.ohiohome.org',
                'email_address'=>'savethedreamohio@ohiohome.org',
                'logo_link'=>'https://ohiohome.org/images/logo@2x.png',
                'datatran_user'=>crypt::encrypt('ouser8'),
                'datatran_password'=>crypt::encrypt('tm6pz&'),
                'owner_type'=>'user',
                'owner_id'=>'2'
            ),
            array(
                'entity_name'=>'Ashtabula County Land Reutilization Corporation.',
                'user_id'=>'3',
                'active'=>'1',
                'address1'=>'25 West Jefferson Street',
                'address2'=>'',
                'city'=>'Jefferson',
                'state_id'=>'36',
                'zip'=>'44047',
                'phone'=>'(440) 576-1450',
                'fax'=>'(440) 576-3221',
                'web_address'=>'http://ashtabulacounty.us',
                'email_address'=>'Landbank@ashtabulacounty.us',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('bula'),
                'datatran_password'=>crypt::encrypt('7aster!'),
                'owner_type'=>'user',
                'owner_id'=>'3'
            ),
            array(
                'entity_name'=>'Belmont County Land Reutilization Corporation.',
                'user_id'=>'4',
                'active'=>'1',
                'address1'=>'101 W. Main Street',
                'address2'=>'',
                'city'=>'St. Clairsville',
                'state_id'=>'36',
                'zip'=>'443950',
                'phone'=>'(740) 699-2155',
                'fax'=>'(740) 699-2156',
                'web_address'=>'http://co.belmont.oh.us',
                'email_address'=>'ginny.favede@co.belmont.oh.us',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('belt'),
                'datatran_password'=>crypt::encrypt('cav$dsh3'),
                'owner_type'=>'user',
                'owner_id'=>'4'
            ),
            array(
                'entity_name'=>'Butler County Land Reutilization Corporation.',
                'user_id'=>'5',
                'active'=>'1',
                'address1'=>'3013 E. 65th St',
                'address2'=>'',
                'city'=>'Hamilton',
                'state_id'=>'36',
                'zip'=>'45011',
                'phone'=>'(513) 877-3166',
                'fax'=>'(513) 785-6366',
                'web_address'=>'http://utlercountyohio.org',
                'email_address'=>'nixn@butlercountyohio.org',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('butler'),
                'datatran_password'=>crypt::encrypt('@mu#1py'),
                'owner_type'=>'user',
                'owner_id'=>'5'
            ),
            array(
                'entity_name'=>'Central Ohio Community Improvement Corporation.',
                'user_id'=>'6',
                'active'=>'1',
                'address1'=>'373 South High St., 15th Floor',
                'address2'=>'',
                'city'=>'Columbus',
                'state_id'=>'36',
                'zip'=>'43215',
                'phone'=>'(614) 525-4937',
                'fax'=>'',
                'web_address'=>'http://cocic.org',
                'email_address'=>'jcrosenberger@cocic.org',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('klin'),
                'datatran_password'=>crypt::encrypt('#osu1&&'),
                'owner_type'=>'user',
                'owner_id'=>'6'
            ),
            array(
                'entity_name'=>'Clark County Land Reutilization Corporation.',
                'user_id'=>'7',
                'active'=>'1',
                'address1'=>'3130 E. Main St, Suite 1A',
                'address2'=>'',
                'city'=>'Springfield',
                'state_id'=>'36',
                'zip'=>'45505',
                'phone'=>'(937) 521-2182',
                'fax'=>'(937) 328-2621',
                'web_address'=>'http://clarkcountyohio.gov',
                'email_address'=>'dfleck@clarkcountyohio.gov',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('ark'),
                'datatran_password'=>crypt::encrypt('lu&clk7'),
                'owner_type'=>'user',
                'owner_id'=>'7'
            ),
            array(
                'entity_name'=>'Columbiana County Land Reutilization Corporation.',
                'user_id'=>'8',
                'active'=>'1',
                'address1'=>'130 W. Maple St.',
                'address2'=>'',
                'city'=>'Lisbon',
                'state_id'=>'36',
                'zip'=>'44432',
                'phone'=>'(330) 424-9078',
                'fax'=>'(330) 424-0577',
                'web_address'=>'http://columbianacodev.org',
                'email_address'=>'therold@columbianacodev.org',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('lumb'),
                'datatran_password'=>crypt::encrypt('ana@poly9'),
                'owner_type'=>'user',
                'owner_id'=>'8'
            ),
            array(
                'entity_name'=>'Cuyahoga County Land Reutilization Corporation.',
                'user_id'=>'9',
                'active'=>'1',
                'address1'=>'323 W Lakeside Ave, Suite 160',
                'address2'=>'',
                'city'=>'Cleveland',
                'state_id'=>'36',
                'zip'=>'44113',
                'phone'=>'(216) 698-8853',
                'fax'=>'(216) 698-8972',
                'web_address'=>'http://cuyahogalandbank.org',
                'email_address'=>'bwhitney@cuyahogalandbank.org',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('hoga'),
                'datatran_password'=>crypt::encrypt('cavs1$'),
                'owner_type'=>'user',
                'owner_id'=>'9'
            ),
            array(
                'entity_name'=>'Erie County Land Reutilization Corporation.',
                'user_id'=>'10',
                'active'=>'1',
                'address1'=>'2900 Columbus Ave., Room 344',
                'address2'=>'',
                'city'=>'Sandusky',
                'state_id'=>'36',
                'zip'=>'44870',
                'phone'=>'(419) 624-6894',
                'fax'=>'(419) 627-6670',
                'web_address'=>'http://eriecounty.oh.gov',
                'email_address'=>'sschell@eriecounty.oh.gov',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('erie'),
                'datatran_password'=>crypt::encrypt('$rommel7'),
                'owner_type'=>'user',
                'owner_id'=>'10'
            ),
            array(
                'entity_name'=>'Fairfield County Land Reutilization Corporation.',
                'user_id'=>'11',
                'active'=>'1',
                'address1'=>'210 E. Main St.',
                'address2'=>'',
                'city'=>'Lancaster',
                'state_id'=>'36',
                'zip'=>'43130',
                'phone'=>'(740) 652-7140',
                'fax'=>'',
                'web_address'=>'http://co.fairfield.oh.us',
                'email_address'=>'jnbahnsen@co.fairfield.oh.us',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('ffd'),
                'datatran_password'=>crypt::encrypt('gen*sher!'),
                'owner_type'=>'user',
                'owner_id'=>'11'
            ),
            array(
                'entity_name'=>'Hamilton County Land Reutilization Corporation.',
                'user_id'=>'12',
                'active'=>'1',
                'address1'=>'299 East 6th St., Suite 2A',
                'address2'=>'',
                'city'=>'Cincinnati',
                'state_id'=>'36',
                'zip'=>'45202',
                'phone'=>'(513) 621-3000',
                'fax'=>'',
                'web_address'=>'http://cincinnatiport.org',
                'email_address'=>'crecht@cincinnatiport.org',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('hami'),
                'datatran_password'=>crypt::encrypt('@@loop88'),
                'owner_type'=>'user',
                'owner_id'=>'12'
            ),
            array(
                'entity_name'=>'Jefferson County Land Reutilization Corporation.',
                'user_id'=>'13',
                'active'=>'1',
                'address1'=>'301 Market Street, Room 105',
                'address2'=>'',
                'city'=>'Stubenville',
                'state_id'=>'36',
                'zip'=>'43952',
                'phone'=>'(740) 283-8572',
                'fax'=>'(740) 284-3343',
                'web_address'=>'http://jeffersoncountyoh.com',
                'email_address'=>'rfenderrpc@jeffersoncountyoh.com',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('effer'),
                'datatran_password'=>crypt::encrypt('ck#gable'),
                'owner_type'=>'user',
                'owner_id'=>'13'
            ),
            array(
                'entity_name'=>'Lake County Land Reutilization Corporation.',
                'user_id'=>'14',
                'active'=>'1',
                'address1'=>'8 N State St Ste 215',
                'address2'=>'',
                'city'=>'Painesville',
                'state_id'=>'36',
                'zip'=>'44077',
                'phone'=>'(440) 350-2133',
                'fax'=>'(440) 350-2113',
                'web_address'=>'http://lakecountylandbank.org',
                'email_address'=>'jmrogers@lakecountylandbank.org',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('lake'),
                'datatran_password'=>crypt::encrypt('&simco35'),
                'owner_type'=>'user',
                'owner_id'=>'14'
            ),
            array(
                'entity_name'=>'Lorain County Port Authority.',
                'user_id'=>'15',
                'active'=>'1',
                'address1'=>'226 Middle Ave',
                'address2'=>'',
                'city'=>'Elyria',
                'state_id'=>'36',
                'zip'=>'44035',
                'phone'=>'(440) 328-2326',
                'fax'=>'(440) 328-2349',
                'web_address'=>'http://loraincounty.us',
                'email_address'=>'pmetzger@loraincounty.us',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('rain'),
                'datatran_password'=>crypt::encrypt('77erie@'),
                'owner_type'=>'user',
                'owner_id'=>'15'
            ),
            array(
                'entity_name'=>'Lucas County Land Reutilization Corporation.',
                'user_id'=>'16',
                'active'=>'1',
                'address1'=>'One Government Center, Suite 580',
                'address2'=>'',
                'city'=>'Toledo',
                'state_id'=>'36',
                'zip'=>'43604',
                'phone'=>'(419) 213-4293',
                'fax'=>'(419) 213-4249',
                'web_address'=>'http://co.lucas.oh.us',
                'email_address'=>'dmann@co.lucas.oh.us',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('cas'),
                'datatran_password'=>crypt::encrypt('$sac4ft'),
                'owner_type'=>'user',
                'owner_id'=>'16'
            ),
            array(
                'entity_name'=>'Mahoning County Land Reutilization Corporation.',
                'user_id'=>'17',
                'active'=>'1',
                'address1'=>'20 W. Federal Street, Suite M-5A',
                'address2'=>'',
                'city'=>'Youngstown',
                'state_id'=>'36',
                'zip'=>'44503',
                'phone'=>'(330) 259-1040',
                'fax'=>'',
                'web_address'=>'http://mahoninglandbank.com',
                'email_address'=>'dflora@mahoninglandbank.com',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('hon'),
                'datatran_password'=>crypt::encrypt('upown@2'),
                'owner_type'=>'user',
                'owner_id'=>'17'
            ),
            array(
                'entity_name'=>'Montgomery County Land Reutilization Corporation.',
                'user_id'=>'18',
                'active'=>'1',
                'address1'=>'130 W. Second St., Suite 1425',
                'address2'=>'',
                'city'=>'Dayton',
                'state_id'=>'36',
                'zip'=>'45402',
                'phone'=>'(937) 531-6921',
                'fax'=>'',
                'web_address'=>'http://mclandbank.com',
                'email_address'=>'mikeg@mclandbank.com',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('montg'),
                'datatran_password'=>crypt::encrypt('go#west6!'),
                'owner_type'=>'user',
                'owner_id'=>'18'
            ),
            array(
                'entity_name'=>'Portage County Land Reutilization Corporation.',
                'user_id'=>'19',
                'active'=>'1',
                'address1'=>'930 Overholt Rd',
                'address2'=>'',
                'city'=>'Kent',
                'state_id'=>'36',
                'zip'=>'44240',
                'phone'=>'(330) 297-3586',
                'fax'=>'(330) 678-8030',
                'web_address'=>'http://kent-ohio.org',
                'email_address'=>'morgantid@kent-ohio.org',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('tage'),
                'datatran_password'=>crypt::encrypt('nxt@qu!'),
                'owner_type'=>'user',
                'owner_id'=>'19'
            ),
            array(
                'entity_name'=>'Richland County Land Reutilization Corporation.',
                'user_id'=>'20',
                'active'=>'1',
                'address1'=>'50 Park Ave. East, Treasurer\'s Office',
                'address2'=>'',
                'city'=>'Mansfield',
                'state_id'=>'36',
                'zip'=>'44902',
                'phone'=>'(419) 755-9795',
                'fax'=>'',
                'web_address'=>'http://richlandcountyoh.us',
                'email_address'=>'ahamrick@richlandcountyoh.us',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('rland'),
                'datatran_password'=>crypt::encrypt('5ny@yank'),
                'owner_type'=>'user',
                'owner_id'=>'20'
            ),
            array(
                'entity_name'=>'Stark County Land Reutilization Corporation.',
                'user_id'=>'21',
                'active'=>'1',
                'address1'=>'110 Central Plaza South, Suite 250',
                'address2'=>'',
                'city'=>'Canton',
                'state_id'=>'36',
                'zip'=>'44702',
                'phone'=>'(330) 489-3258',
                'fax'=>'',
                'web_address'=>'http://starkcountyohio.gov',
                'email_address'=>'aazumbar@starkcountyohio.gov',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('stark'),
                'datatran_password'=>crypt::encrypt('stk!7ohmy'),
                'owner_type'=>'user',
                'owner_id'=>'21'
            ),
            array(
                'entity_name'=>'Summit County Land Reutilization Corporation.',
                'user_id'=>'22',
                'active'=>'1',
                'address1'=>'175 South Main St',
                'address2'=>'',
                'city'=>'Akron',
                'state_id'=>'36',
                'zip'=>'44308',
                'phone'=>'(330) 643-7769',
                'fax'=>'(330) 643-2886',
                'web_address'=>'http://summitlandbank.org',
                'email_address'=>'pbravo@summitlandbank.org',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('mmit'),
                'datatran_password'=>crypt::encrypt('red!grn@4'),
                'owner_type'=>'user',
                'owner_id'=>'22'
            ),
            array(
                'entity_name'=>'Trumbull County Land Reutilization Corporation.',
                'user_id'=>'23',
                'active'=>'1',
                'address1'=>'147 W. Market Street',
                'address2'=>'',
                'city'=>'Warren',
                'state_id'=>'36',
                'zip'=>'44481',
                'phone'=>'(330) 469-6828',
                'fax'=>'',
                'web_address'=>'http://tnpwarren.org',
                'email_address'=>'lisa@tnpwarren.org',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('mbull'),
                'datatran_password'=>crypt::encrypt('yt*oh@@'),
                'owner_type'=>'user',
                'owner_id'=>'23'
            ),
            array(
                'entity_name'=>'Allen County Land Reutilization Corporation.',
                'user_id'=>'30',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user',
                'owner_id'=>'30'
            ),
            array(
                'entity_name'=>'Clinton County Land Reutilization Corporation.',
                'user_id'=>'31',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user',
                'owner_id'=>'31'
            ),
            array(
                'entity_name'=>'Crawford County Land Reutilization Corporation.',
                'user_id'=>'32',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user',
                'owner_id'=>'32'
            ),
            array(
                'entity_name'=>'Lawrence County Land Reutilization Corporation.',
                'user_id'=>'33',
                'owner_id'=>'33',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Licking County Land Reutilization Corporation.',
                'user_id'=>'34',
                'owner_id'=>'34',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Marion County Land Reutilization Corporation.',
                'user_id'=>'35',
                'owner_id'=>'35',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Morrow County Land Reutilization Corporation.',
                'user_id'=>'36',
                'owner_id'=>'36',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Ottawa County Land Reutilization Corporation.',
                'user_id'=>'37',
                'owner_id'=>'37',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Perry County Land Reutilization Corporation.',
                'user_id'=>'38',
                'owner_id'=>'38',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Ross County Land Reutilization Corporation.',
                'user_id'=>'39',
                'owner_id'=>'39',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Sandusky County Land Reutilization Corporation.',
                'user_id'=>'40',
                'owner_id'=>'40',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Scioto County Land Reutilization Corporation.',
                'user_id'=>'41',
                'owner_id'=>'41',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Seneca County Land Reutilization Corporation.',
                'user_id'=>'42',
                'owner_id'=>'42',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Shelby County Land Reutilization Corporation.',
                'user_id'=>'43',
                'owner_id'=>'43',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Van Wert County Land Reutilization Corporation.',
                'user_id'=>'44',
                'owner_id'=>'44',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'Williams County Land Reutilization Corporation.',
                'user_id'=>'45',
                'owner_id'=>'45',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            ),
            array(
                'entity_name'=>'The Historic Agency',
                'user_id'=>'46',
                'owner_id'=>'46',
                'active'=>'1',
                'address1'=>'NA',
                'address2'=>'',
                'city'=>'NA',
                'state_id'=>'36',
                'zip'=>'NA',
                'phone'=>'NA',
                'fax'=>'',
                'web_address'=>'NA',
                'email_address'=>'NA',
                'logo_link'=>'',
                'datatran_user'=>crypt::encrypt('NA'),
                'datatran_password'=>crypt::encrypt('NA'),
                'owner_type'=>'user'
            )
        );

        \Illuminate\Support\Facades\DB::table('entities')->insert($entitiesData);
    }
}
