<?php

use Illuminate\Database\Seeder;

class ExpenseCategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $expenseCategoriesData = array(
              array(
             'id'=>'1',
             'hfa'=>'1',
             'expense_category_name'=>'Expense Categories',
             'parent_id'=>'0',
             'active'=>'1',
             'color_hex'=>'',
             'trans_color_hex'=>'',
             'advance_color_hex'=>'',
             'advance_trans_color_hex'=>'',
             ),
              array(
             'id'=>'2',
             'hfa'=>'1',
             'expense_category_name'=>'Acquisition',
             'parent_id'=>'1',
             'active'=>'1',
             'color_hex'=>'#005186',
             'trans_color_hex'=>'',
             'advance_color_hex'=>'#5a7c92',
             'advance_trans_color_hex'=>'',
             ),
              array(
             'id'=>'3',
             'hfa'=>'1',
             'expense_category_name'=>'Pre-Demo',
             'parent_id'=>'1',
             'active'=>'1',
             'color_hex'=>'#4D4D4D',
             'trans_color_hex'=>'',
             'advance_color_hex'=>'#696868',
             'advance_trans_color_hex'=>'',
             ),
              array(
             'id'=>'4',
             'hfa'=>'1',
             'expense_category_name'=>'Demolition',
             'parent_id'=>'1',
             'active'=>'1',
             'color_hex'=>'#5DA5DA',
             'trans_color_hex'=>'',
             'advance_color_hex'=>'#adc7da',
             'advance_trans_color_hex'=>'',
             ),
              array(
             'id'=>'5',
             'hfa'=>'1',
             'expense_category_name'=>'Greening',
             'parent_id'=>'1',
             'active'=>'1',
             'color_hex'=>'#60BD68',
             'trans_color_hex'=>'',
             'advance_color_hex'=>'#8bad8e',
             'advance_trans_color_hex'=>'',
             ),
              array(
             'id'=>'6',
             'hfa'=>'1',
             'expense_category_name'=>'Maintenance',
             'parent_id'=>'1',
             'active'=>'1',
             'color_hex'=>'#FAA43A',
             'trans_color_hex'=>'',
             'advance_color_hex'=>'#d0b18a',
             'advance_trans_color_hex'=>'',
             ),
              array(
             'id'=>'7',
             'hfa'=>'1',
             'expense_category_name'=>'Administration',
             'parent_id'=>'1',
             'active'=>'1',
             'color_hex'=>'#F17CB0',
             'trans_color_hex'=>'',
             'advance_color_hex'=>'#ea9aa7',
             'advance_trans_color_hex'=>'',
             ),
              array(
             'id'=>'8',
             'hfa'=>'1',
             'expense_category_name'=>'Other',
             'parent_id'=>'1',
             'active'=>'1',
             'color_hex'=>'#B276B2',
             'trans_color_hex'=>'',
             'advance_color_hex'=>'#c3b0c3',
             'advance_trans_color_hex'=>'',
             ),
              array(
             'id'=>'9',
             'hfa'=>'1',
             'expense_category_name'=>'NIP Loan Payoff',
             'parent_id'=>'1',
             'active'=>'1',
             'color_hex'=>'#B2912F',
             'trans_color_hex'=>'',
             'advance_color_hex'=>'#bfb28c',
             'advance_trans_color_hex'=>'',
             )
        );
        DB::table('expense_categories')->insert($expenseCategoriesData);
    }
}
