<?php

use Illuminate\Database\Seeder;

class UserRolesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $userRolesData = [

            [
                'role_id'=>2,
                'user_id'=>1
            ],
            [
                'role_id'=>2,
                'user_id'=>2
            ],
            [
                'role_id'=>4,
                'user_id'=>3
            ],
            [
                'role_id'=>4,
                'user_id'=>4
            ],
            [
                'role_id'=>4,
                'user_id'=>5
            ],
            [
                'role_id'=>4,
                'user_id'=>6
            ],
            [
                'role_id'=>4,
                'user_id'=>7
            ],
            [
                'role_id'=>4,
                'user_id'=>8
            ],
            [
                'role_id'=>4,
                'user_id'=>9
            ],
            [
                'role_id'=>4,
                'user_id'=>10
            ],
            [
                'role_id'=>4,
                'user_id'=>11
            ],
            [
                'role_id'=>4,
                'user_id'=>12
            ],
            [
                'role_id'=>4,
                'user_id'=>13
            ],
            [
                'role_id'=>4,
                'user_id'=>14
            ],
            [
                'role_id'=>4,
                'user_id'=>15
            ],
            [
                'role_id'=>4,
                'user_id'=>16
            ],
            [
                'role_id'=>4,
                'user_id'=>17
            ],
            [
                'role_id'=>4,
                'user_id'=>18
            ],
            [
                'role_id'=>4,
                'user_id'=>19
            ],
            [
                'role_id'=>4,
                'user_id'=>20
            ],
            [
                'role_id'=>4,
                'user_id'=>21
            ],
            [
                'role_id'=>4,
                'user_id'=>22
            ],
            [
                'role_id'=>4,
                'user_id'=>23
            ],
            [
                'role_id'=>2,
                'user_id'=>24
            ],
            [
                'role_id'=>2,
                'user_id'=>25
            ],
            [
                'role_id'=>2,
                'user_id'=>26
            ],
            [
                'role_id'=>2,
                'user_id'=>27
            ],
            [
                'role_id'=>2,
                'user_id'=>28
            ],
            [
                'role_id'=>2,
                'user_id'=>29
            ],
            [
                'role_id'=>5,
                'user_id'=>2
            ],
            [
                'role_id'=>5,
                'user_id'=>1
            ]
        ];
        DB::table('users_roles')->insert($userRolesData);

        $userRolesData = [

            [
                'role_id'=>7,
                'user_id'=>2
            ],
            [
                'role_id'=>8,
                'user_id'=>2
            ],
            [
                'role_id'=>9,
                'user_id'=>2
            ],
            [
                'role_id'=>10,
                'user_id'=>6
            ],
            [
                'role_id'=>11,
                'user_id'=>6
            ],
            [
                'role_id'=>12,
                'user_id'=>6
            ],
            [
                'role_id'=>7,
                'user_id'=>1
            ],
            [
                'role_id'=>8,
                'user_id'=>1
            ],
            [
                'role_id'=>9,
                'user_id'=>1
            ],
            [
                'role_id'=>10,
                'user_id'=>1
            ],
            [
                'role_id'=>11,
                'user_id'=>9
            ],
            [
                'role_id'=>12,
                'user_id'=>9
            ],
            [
                'role_id'=>71,
                'user_id'=>2
            ],
            [
                'role_id'=>72,
                'user_id'=>2
            ],
            [
                'role_id'=>73,
                'user_id'=>2
            ],
            [
                'role_id'=>71,
                'user_id'=>28
            ],
            [
                'role_id'=>72,
                'user_id'=>28
            ],
            [
                'role_id'=>73,
                'user_id'=>28
            ],
            [
                'role_id'=>74,
                'user_id'=>65
            ],
            [
                'role_id'=>75,
                'user_id'=>65
            ],
        ];

        \Illuminate\Support\Facades\DB::table('users_roles')->insert($userRolesData);
    }
}
