<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUnitProgramsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (! Schema::hasTable('unit_programs')) {
            Schema::create('unit_programs', function (Blueprint $table) {
                $table->increments('id');
                $table->integer('unit_key')->nullable();
                $table->integer('unit_id')->nullable();
                $table->integer('program_key')->nullable();
                $table->integer('program_id')->nullable();
                $table->integer('audit_id')->nullable();
                $table->integer('monitoring_key')->nullable();
                $table->nullableTimestamps();
                $table->integer('project_id')->nullable();
                $table->integer('development_key')->nullable();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('unit_programs');
    }
}
