<?php

return [

  'car_status'        => [
    'car-report-selection-all'                   => 'ALL CAR REPORT STATUSES',
    'car-report-selection-draft'                 => 'DRAFT',
    'car-report-selection-to-manager'            => 'PENDING MANAGER REVIEW',
    'car-report-selection-declined'              => 'DECLINED',
    'car-report-selection-approved-with-changes' => 'APPROVED WITH CHANGES',
    'car-report-selection-approved'              => 'APPROVED',
    'car-report-selection-to-pm'                 => 'SENT TO PROPERTY CONTACT',
    'car-report-selection-viewed'                => 'PROPERTY VIEWED IN PERSON',
    'car-report-selection-resolved'              => 'ALL ITEMS RESOLVED',
  ],
  'ehs_status'        => [
    'ehs-report-selection-all'                   => 'ALL EHS REPORT STATUSES',
    'ehs-report-selection-draft'                 => 'DRAFT',
    'ehs-report-selection-to-manager'            => 'SENT TO MANAGER REVIEW',
    'ehs-report-selection-declined'              => 'DECLINED',
    'ehs-report-selection-approved-with-changes' => 'APPROVED WITH CHANGES',
    'ehs-report-selection-approved'              => 'APPROVED',
    'ehs-report-selection-to-pm'                 => 'SENT TO PROPERTY CONTACT',
    'ehs-report-selection-viewed'                => 'PROPERTY VIEWED IN PERSON',
    'ehs-report-selection-resolved'              => 'ALL ITEMS RESOLVED',
  ],
  '8823_status'       => [
    '8823-report-selection-all'                   => 'ALL 8823 REPORT STATUSES',
    '8823-report-selection-draft'                 => 'DRAFT',
    '8823-report-selection-to-manager'            => 'SENT TO MANAGER REVIEW',
    '8823-report-selection-declined'              => 'DECLINED',
    '8823-report-selection-approved-with-changes' => 'APPROVED WITH CHANGES',
    '8823-report-selection-approved'              => 'APPROVED',
    '8823-report-selection-to-pm'                 => 'SENT TO PROPERTY CONTACT',
    '8823-report-selection-viewed'                => 'PROPERTY VIEWED IN PERSON',
    '8823-report-selection-resolved'              => 'ALL ITEMS RESOLVED',
  ],

  'car_approval_type' => [
    'car-report-selection-all'                   => 0,
    'car-report-selection-draft'                 => 1,
    'car-report-selection-to-manager'            => 2,
    'car-report-selection-declined'              => 3,
    'car-report-selection-approved-with-changes' => 4,
    'car-report-selection-approved'              => 5,
    'car-report-selection-to-pm'                 => 6,
    'car-report-selection-viewed'                => 7,
    'car-report-selection-resolved'              => 9,
  ],
  'ehs_approval_type' => [
    'ehs-report-selection-all'                   => 0,
    'ehs-report-selection-draft'                 => 1,
    'ehs-report-selection-to-manager'            => 2,
    'ehs-report-selection-declined'              => 3,
    'ehs-report-selection-approved-with-changes' => 4,
    'ehs-report-selection-approved'              => 5,
    'ehs-report-selection-to-pm'                 => 6,
    'ehs-report-selection-viewed'                => 7,
    'ehs-report-selection-resolved'              => 9,
  ],
  '8823_approval_type' => [
    '8823-report-selection-all'                   => 0,
    '8823-report-selection-draft'                 => 1,
    '8823-report-selection-to-manager'            => 2,
    '8823-report-selection-declined'              => 3,
    '8823-report-selection-approved-with-changes' => 4,
    '8823-report-selection-approved'              => 5,
    '8823-report-selection-to-pm'                 => 6,
    '8823-report-selection-viewed'                => 7,
    '8823-report-selection-resolved'              => 9,
  ],

];
